from PyQt5.Qt import *
import sys

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = QWidget()
    button = QPushButton(window)
    button.setText('Menu')
    button.setFlat(True)
    menu = QMenu()
    menu_lv2 = QMenu(menu)
    menu_lv2.setTitle('最近打开')
    action1 = QAction()
    action1.setText('新建')
    action1.triggered.connect(lambda: print('新建'))
    action2 = QAction()
    action2.setText('打开')
    action2.triggered.connect(lambda: print('打开'))
    action_recent_open = QAction('最近打开')
    menu_lv2.addAction(action_recent_open)
    menu.addAction(action1)
    menu.addSeparator()
    menu.addAction(action2)
    menu.addMenu(menu_lv2)
    button.setMenu(menu)
    window.show()
    sys.exit(app.exec())
